name: Coding standards

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Spelling
        uses: UnicornGlobal/spellcheck-github-actions@0.4.0
          
