name: Coding standards

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  Spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check spelling
        uses: typoci/spellcheck-action@master
          
