name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install depdendencies
        working-directory: ./client
        run: npm install -ci
      
      - name: Build website
        working-directory: ./client
        run: npm run build
      
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist

  Server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "filminc"
          heroku_email: "somfic@gmail.com"
          appdir: server
