name: Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install depdendencies
        working-directory: ./client
        run: npm install -ci
      
      - name: Build client
        working-directory: ./client
        run: npm run build
      
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
