name: SonarQube

on:
  push:
    branches: [ main ]
    
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
         host: ${{ secrets.SONARQUBE_HOST }}
         login: ${{ secrets.SONARQUBE_TOKEN }}
