name: Code tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  server:
    name: Test application on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      run: npm install -ci
      working-directory: ./client

    - name: Build frontend
      working-directory: ./client
      run: npm run build

    - name: Install backend dependencies
      run: npm install -ci
      working-directory: ./server

    - name: Build backend
      run: npm run build --if-present
      working-directory: ./server
    
    - name: Test application
      run: npm test
      working-directory: server
      env:
        CI: true
    
          
